# Should throw an error
a1 <- 3
print a1